# Generated by Django 3.1.7 on 2021-03-28 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='images',
            new_name='image',
        ),
    ]
