# Generated by Django 3.1.13 on 2021-11-25 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubPreCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='Category/Sub-Category/Sub-Pre-Category')),
                ('show_in_dropdown', models.BooleanField(default=True)),
                ('SubCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubCategory', to='Category.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='SubPostCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='Category/Sub-Category/Sub-Post-Category/Sub-Post-Category')),
                ('show_in_dropdown', models.BooleanField(default=True)),
                ('SubPreCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubPreCategory', to='Category.subprecategory')),
            ],
        ),
    ]
