# Generated by Django 3.1.13 on 2021-11-25 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0003_subpostcategory_subprecategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Sub-Category', 'verbose_name_plural': 'Sub-Categories'},
        ),
        migrations.AlterModelOptions(
            name='subpostcategory',
            options={'verbose_name': 'Sub-Post-Category', 'verbose_name_plural': 'Sub-Post-Categories'},
        ),
        migrations.AlterModelOptions(
            name='subprecategory',
            options={'verbose_name': 'Sub-Pre-Category', 'verbose_name_plural': 'Sub-Pre-Categories'},
        ),
    ]
